# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
# 0.16.0 为最低支持的 Loader 版本（fabric.mod.json depends 随此值展开）
loader_version=0.16.0
# Mod Properties
mod_version=0.52.325325-fix0b_0+Fab1.21.1-build1
maven_group=org.exampl
archives_base_name=chocolate-server-tacz-match-mod
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.115.6+1.21.1
